### ISSUE TITLE
Add the new 64px scale.

### ISSUE THREAD

**Issue by zeromero-dev** [cadgerfeast/pixel-icons#21]
The package is definitely missing on one of the most popular scales - 64px by 64px. 
Need to add this scale to the package and upscale images accordingly.

**Comment by cadgerfeast** [comment]
I agree, the idea was to create small pixel-arts icons (`15px`) and then to upscale from a factor. (`10`).
It might be better to go for the standard `16px` icons, then we could do a factor (`2`).
I'll get a look about this (It would imply some changes on the existing icons)

**Comment by cadgerfeast** [comment]
This has been fixed with version `0.0.14`.
